### PR TITLE
Add hashPrefix option

### PR DESCRIPTION
**Pull request by jessethomson**
**Background**

The webpack `css-loader` has support for a `hashPrefix` option to "[allow to add custom hash to generate more unique classes](https://webpack.js.org/loaders/css-loader/#hashprefix)".

In `postcss-modules`, we use the `generic-names` package, which [already supports `hashPrefix`](https://github.com/css-modules/generic-names/blob/d57cb1c4dbf391fb68be9e5f38e68ad1d5a0f2d9/index.js#L19-L20).

**Change**

This change simply adds a new `hashPrefix` option to `postcss-modules`, which is forwarded to the `generic-names` generator.

This change is backwards compatible feature and should go out in a minor release.

### CODE REVIEW

**Comment by jessethomson** [comment]
I'm not sure why, but two tests unrelated to this change fail in Node 6 and 7 because autoprefixer is adding an unexpected webkit value

Screen Shot 2019-09-13 at 11 02 07 AM

Screen Shot 2019-09-13 at 11 01 59 AM

**Comment by outpunk** [comment]
@jessethomson Thanks a lot for the contribution, I really appreciate it! I'll take a look at this a bit later (in one or two days)

**Comment by jessethomson** [comment]
Awesome, thanks for helping me make my first open source code contribution!

**Comment by outpunk** [comment]
I will release the new version by the end of the week

**Comment by jessethomson** [comment]
Great, I look forward to it! Thanks for all you do!

**Comment by jessethomson** [comment]
Can we get a new version released with this change? No rush. I know people have lives outside of open source projects so whenever you get some free time would be great 😄

**Comment by outpunk** [comment]
Oh, crap! I have completely forgot about this. Thank you for reminding me. 

I’m away from my laptop today, will release in a couple of days.

**Comment by outpunk** [comment]
@jessethomson published. Sorry for keeping you waiting.

**Pull request merged**
