### PR TITLE
feat: expose export tokens to other plugins

### LINKED ISSUE #29: Expose JSON data to other PostCSS plugins?
It might be good to use _Result#messages_ to store the JSON map of classes and generated class names. That way the data can be easily accessed by other plugins.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #29

### CODE REVIEW

**Comment by outpunk** [comment]
Published. @evilebottnawi thanks!

**Comment by evilebottnawi** [comment]
@outpunk Looks need update https://github.com/css-modules/postcss-modules/blob/master/CHANGELOG.md

**Comment by outpunk** [comment]
@evilebottnawi Sorry, pushed the update and republished release. I should never publish anything in the night time :(

**Comment by DoctaCloak** [comment]
This was merged with failing CI?  Is this plugin still good to use?

**Comment by outpunk** [comment]
@DoctaCloak the failure is not related to this PR. I just have no time to fix it right now. The plugin works as intended, the issue happens during automated testing only.

**Pull request merged**
